### ISSUE TITLE
Big truck shoots its own tyre

### ISSUE THREAD

**Issue by hemebond** [RennyC4/RenRacer#2]
At certain angles the machineguns on the big truck can end up shooting its own tyre.
![image](https://github.com/RennyC4/RenRacer/assets/424218/57c5eac9-a1b6-41b3-bcf3-6171a290abac)

**Comment by RennyC4** [comment]
Tested and it seems to be working fine. Make sure you're using the latest commit, bullets now use dimension_hit/solid now to pass through the cars bounding box stuff
